### ISSUE TITLE
Firefox autofocus

### ISSUE THREAD

**Issue by bradleypriest** [percy/percy-capybara#114]
Hey team, ever since we've upgraded to v4 of this library we're seeing a lot of mis-diffs that didn't occur before around the `autofocus` HTML attribute.

An input with the `autofocus` attribute will sometimes be focussed and sometimes not be focussed in the screenshot, causing regular false positives back and forth.

A quick search across the percy-capybara and percy-agent libraries didn't return anything around dealing with focus, any ideas?

**Comment by djones** [comment]
Hi @bradleypriest, thanks for bringing this up. It's not an SDK related issue but rather one in our rendering infrastructure, specifically for Firefox. You can see this sort of issue on our own builds here: https://percy.io/percy/percy-web/builds/2696661

We're looking into it and I'll update you as we find out more.

**Comment by djones** [comment]
Hi @bradleypriest, we've shipped a fix for this. You might see some diffs going from broken to fixed initially.

Let's wait a week and call this issue resolved if you don't see any fixed to broken diffs in that time. Thanks!

**Comment by djones** [comment]
Hi @bradleypriest, I'm going to close this one now. We haven't seen this issue since we shipped a fix. If it's still an issue for you, feel free to reply and I'll reopen it.
