### ISSUE TITLE
Styles not rendering in the screenshots

### ISSUE THREAD

**Issue by markcatley** [percy/percy-capybara#126]
Hi,

I am having trouble with the screenshots not showing the styles. The command I'm running is `yarn run percy exec -- ./bin/rails test:system`. I have tried it both in CI on Github Actions, and locally on macOS. Screenshots using the `take_screenshot` rails method works correctly.

I am not sure what information I give to help, but:
- I am using firefox headless
- I am using Rails 6.0.2.1
- Styles are compiled from scss using webpacker.

What other information would be helpful?

Thank you in advance for your help.

**Comment by Robdel12** [comment]
Hey @markcatley! This typically happens when building with webpack in dev mode. Webpack 4 introduced a change where CSS is generated as a `blob:` asset, which cannot be captured (this also happens with source maps enabled too). I'd try disabling source maps in tests. If that doesn't work, try building as production.

**Comment by markcatley** [comment]
Thanks, @Robdel12.

I added the following to my `webpacker.yml` and it's looking a lot better:
```yaml
test:
  ...
  # Extract and emit a css file
  extract_css: true
```
Perhaps that needs to go in your documentation somewhere? Or is it and I missed it?

I still have some visual issues in percy that are not present if I take a screenshot using the `take_screenshot`. Particularly around special characters. One example is that instead of displaying an m dash correctly I am seeing â€”. I have similar issues with a copywrite symbol.

Any ideas?

**Comment by Robdel12** [comment]
Hey @markcatley! I had a half typed response here that I never sent through, sorry about that! I have updated the docs to reflect the webpacker changes: https://docs.percy.io/docs/capybara#section-missing-styles

As for special chars showing up as `â€` -- that usually means there's a missing charset meta tag in the `<head>`. If you could reach out to support (via intercom), we can take a look at a few specific snapshots to verify.

**Comment by markcatley** [comment]
Thanks for the reply. I had started to wonder 😊. 

I had thought that maybe adding a chat set tag to the head might help. I was going to find time today to try it out. I’ll give it a go and let you know.
