### ISSUE TITLE
Canvas elements appear empty

### ISSUE THREAD

**Issue by mupkoo** [percy/percy-capybara#128]
In one of our apps, we are using Chart.js for rendering charts, but they appear empty. I couldn't find any information in the docs, if I need to do something special to get them to work.

I can confirm that the JavaScript is running, because all other components are rendering correctly except the chart.

**Comment by Robdel12** [comment]
Hey @mupkoo -- funny you just closed this. This PR will solve this: https://github.com/percy/percy-agent/pull/483

**Comment by mupkoo** [comment]
Ha! That is awesome! 

I closed the issue, because I was explained how the current agent was working, but nice to see that the canvas elements will be part of our builds :)

**Comment by mupkoo** [comment]
Just tested it. Works really nice 👍

**Comment by Robdel12** [comment]
Ahh, I love hearing that! 😃
