### ISSUE TITLE
Node version requirement

### ISSUE THREAD

**Issue by daveteal** [percy/percy-capybara#172]
It's not mentioned at all in the documentation that node v12+ is required now.

`Node v10.24.0 is not supported. Percy only supports the current LTS of Node. Please upgrade to Node v12+`

**Comment by Robdel12** [comment]
That's true, we only support what node supports in their LTS: https://nodejs.org/en/about/releases/

This would have been true for `@percy/agent` but we deprecated the package & stopped development on it before april of this year (when Node dropped support for v10.x)
