### ISSUE TITLE
uninitialized constant Percy

### ISSUE THREAD

**Issue by Paxa** [percy/percy-capybara#3]
Following docs here https://percy.io/docs/capybara I got this error

```
uninitialized constant Percy (NameError)
```

Solution is to require percy gem in spec_helper in :

```ruby
require 'percy'
require 'percy/capybara'
require 'percy/capybara/rspec'
```

I think when we require `percy/capybara/rspec` it should require `percy` too

**Comment by Paxa** [comment]
Also if use build in initializer (`percy/capybara/rspec`) then it will call `Percy::Capybara.initialize_build` before tests start. So `Percy::Capybara::Client` will be disabled by default and it will quietly skip snapshots and has no effect

**Comment by Paxa** [comment]
Ok, my bad. I didn't read docs well. But it will be easier if `percy-capybara` will print some message when it is disabled. E.g.
```
* percy-capybara is disabled
........
Finished in 32.64 seconds (files took 1.38 seconds to load)
```

**Comment by Paxa** [comment]
One more thing:
How to test pages on mobile? I change windows size in poltergeist but on percy it shows same as desktop

**Comment by fotinakis** [comment]
Hey @Paxa — glad you figured it out! :+1: Yes, we need to add some console output from the Percy Capybara client so the getting started process is a little easier.

For mobile responsive testing, that's something we have plans for an would like to get working soon, but no exact details on when it will be done. For the best performance and parallelization, we perform all rendering in Percy as a service (not inside your poltergeist tests), so we will be adding an option for you to specify which different window sizes your Percy project will use. If you send me a quick email to team@percy.io, I'll make sure you're on the beta testing list for that feature.
