### ISSUE TITLE
Assets missing with custom sprockets config

### ISSUE THREAD

**Issue by fotinakis** [percy/percy-capybara#39]
With this config:

```ruby
config.assets.paths << Rails.root.join(
  "vendor/assets/bower_components/app-assets/dist/assets/images").to_s
```

Then image is then correctly referenced like:
```ruby
image_path('some-image.svg')
```

For some reason, the Percy resource URL ends up being:

```
/app-assets/dist/assets/images/some-image.svg
```
instead of:
```
/assets/images/some-image.svg
```
so the images are broken in percy.

We use `ActionController::Base.helpers.asset_path` (https://github.com/percy/percy-capybara/blob/v3.0.2/lib/percy/capybara/loaders/sprockets_loader.rb#L50) to find the asset path, perhaps it is wrong in this case?

**Comment by akshayrawat** [comment]
Sounds right. Let me know if you help reproducing this. 👍

**Comment by fotinakis** [comment]
Fixed with custom loader workaround:

```ruby
assets_dir = 'vendor/assets/bower_components/app-assets/dist/assets/images'

class CustomLoader < Percy::Capybara::Loaders::SprocketsLoader
  def build_resources
    resources = Percy::Capybara::Loaders::BaseLoader.new._resources_from_dir(
      assets_dir,
      base_url: '/assets',
    )
    super + resources
  end
end

# Then, in spec_helper.rb:
Percy::Capybara.use_loader(CustomLoader)
```

**Comment by djones** [comment]
I'm closing this issue as the new `percy-capybara` 4.x version does not use loaders and therefore avoids these issues 🎉 

An [upgrade guide from v3 to v4 is available](https://docs.percy.io/docs/upgrading-to-v4) for those interested in upgrading.
