### ISSUE TITLE
Percy should support uploading assets from public/

### ISSUE THREAD

**Issue by tristanoneil** [percy/percy-capybara#4]
Currently if you reference assets that are located in `public/` the Percy client doesn't upload anything at all. It seems this is caused because the client only supports external resources or assets served up by Sprockets. It'd be nice if the [Sprockets loader](https://github.com/percy/percy-capybara/blob/master/lib/percy/capybara/loaders/sprockets_loader.rb#L33) supported assets located and referenced in `public/`.

**Comment by fotinakis** [comment]
Done! https://github.com/percy/percy-capybara/commit/8822ed0e82065bdc1b86ab900e59521cbbc1a01f

This has been pushed as v1.2.0 of the gem. Thanks for the feedback.
