### ISSUE TITLE
Warning being seen from Faraday due to unexpected middleware

### ISSUE THREAD

**Issue by rsimha-amp** [percy/percy-capybara#45]
This started recently, presumably due to `faraday` receiving a version bump.

```
WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
```

See https://github.com/percy/percy-capybara/blob/68a6dc2257dad18d1237c3c9772c1ee073e206d0/percy-capybara.gemspec#L31

**Comment by rsimha-amp** [comment]
Here's an example of the warning we're seeing. Note that all our logs are silenced, and the only ones being printed are by Percy.

https://travis-ci.org/ampproject/amphtml/jobs/257300515#L649

**Comment by timhaines** [comment]
This logging really comes from our percy-client gem.  The logging is resolved if we switch the order of [these two lines](https://github.com/percy/percy-client/blob/master/lib/percy/client/connection.rb#L65-L66).  

However, that breaks [this test](https://github.com/percy/percy-client/blob/master/spec/lib/percy/client/connection_spec.rb#L16) which I haven't been able to figure out just now.  We'll work on this @rsimha-amp.

**Comment by timhaines** [comment]
@rsimha-amp This should be resolved now with the release of [percy-client 1.13.5](https://github.com/percy/percy-client/releases/tag/v1.13.5).  If you update your gem bundle and still see issues with this, please let me know.

**Comment by rsimha-amp** [comment]
Cool, will do. Thanks!

**Comment by rsimha-amp** [comment]
I just checked our logs, and the errors are gone. Thanks for the fix.
