### ISSUE TITLE
How to ignore certain asset files?

### ISSUE THREAD

**Issue by kaelig** [percy/percy-capybara#47]
Is it possible to ignore certain files under my project's assets directory? There are some cache files as well as other things in there, and they don't need to be uploaded (they're in a dot folder.

Alternatively I'll make a directory specifically for Percy that only contains the appropriate assets but I just wanted to check before I go down that road.

**Comment by fotinakis** [comment]
Hey @kaelig, there is unfortunately not an option for that in the filesystem_loader right now. Creating a structured temp directory, which from our conversation sounds like you may have to do anywhat, would definitely fix that.
