### ISSUE TITLE
Using Percy snaps in view tests

### ISSUE THREAD

**Issue by doutatsu** [percy/percy-capybara#54]
I am trying to figure out if its possible to use Percy snaps in view tests. As Capybara works to a certain degree in there, I'd imagine Percy would as well. 

I use `Capybara::Node::Simple.new(rendered)` for `page` and pass it as well to Percy. But I get `current_url` method missing. Looking into Percy source code I can't find the instance where this is being called to understand the reason.

**Comment by djones** [comment]
Hi @doutatsu, the `current_url` call might be from here: https://github.com/percy/percy-capybara/blob/37109a3d627ee1a94d2d8e546bd734d6bf88f0ce/lib/percy/capybara/loaders/base_loader.rb#L76-L84

I'm curious to learn more about your use case. A bit more context around `Capybara::Node::Simple.new` and how the `percy.snapshot` call currently fits in would be really useful.

Cheers.

**Comment by doutatsu** [comment]
Hi @djones, thanks for a speedy reply. Not sure how I missed that code.

We use Percy snaps in Integration tests, where Capybara has full capacity. But we had a couple view tests, in one of which we used `Capybara::Node::Simple.new` to be able to use `.find` method on Capybara. 

But there was a need to have a Percy snap in the view test itself, so I thought I'd reuse this object, but it seems its not enough for Percy 🤔 

So as mentioned before, I wonder if it is possible to make snaps in view tests or I have to use an Integration test (Which inherits from `ActionDispatch::IntegrationTest`)

**Comment by djones** [comment]
My sense is this should be possible so long you're able to get the DOM and resources required to load that DOM. I don't have any experience with testing views in Capybara though.

I'd like to get a minimal view test example going so I can take a look at how we might modify `percy-capybara` to make it work out of the box for this use case.

Are you doing something similar to this? https://robots.thoughtbot.com/use-capybara-on-any-html-fragment-or-page

**Comment by doutatsu** [comment]
Hey @djones was wondering if you had any more thoughts on this? That work has been put on hold due to this, but I'd like to either get this working or confirm that its impossible
