### ISSUE TITLE
Webpacker 4

### ISSUE THREAD

**Issue by vitalinfo** [percy/percy-capybara#76]
After upgrade Webpacker 4 have problem with screenshots on pages switch are using pack CSS.
Does it known issue?

**Comment by djones** [comment]
Hi @vitalinfo, sorry about the issues here. Which version of percy-capybara are you using?

**Comment by vitalinfo** [comment]
@djones 3.2.0

**Comment by vitalinfo** [comment]
@djones looks like I've found work around with webpacker configuration

**Comment by djones** [comment]
@vitalinfo good to hear!

Just a little follow up here... we've been working on v4, a new major version of `percy-capybara`. We've [pre-released this new version](https://rubygems.org/gems/percy-capybara) and it does away with loaders, therefore your webpacker configuration shouldn't matter at all.

Here is our upgrade guide to help you [migrate from percy-capybara v3 to v4](https://docs.percy.io/docs/upgrading-to-v4).

**Comment by vitalinfo** [comment]
Thanks

**Comment by doutatsu** [comment]
@vitalinfo Could you provide what you did with your configuration? I am facing the same issue and v4 upgrade didn't help me I am afraid @djones

**Comment by vitalinfo** [comment]
@doutatsu I've added `extract_css: true` to the `test` webpacker.yml config
